AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app

Resources:
  UserCartApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: carts
      Handler: index.handler
      Runtime: nodejs10.x
      Timeout: 5

      Events:
        CatalogEndpointRoot:
          Properties:
            Method: any
            Path: /user/cart/
          Type: Api

  CatalogAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: catalog
      Handler: index.handler
      Runtime: nodejs10.x
      Timeout: 5
      
      Events:
        CatalogEndpointRoot:
          Properties:
            Method: any
            Path: /catalog/
          Type: Api
